package eus.ferpinan.kafka_beginner_course_consumer.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

/**
 * Represents the revision identifiers for a Wikimedia page change.
 * <p>
 * This class maps the transition between the previous state of a page
 * and the current state produced by the event.
 * </p>
 */
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class Revision {

    /**
     * The ID of the revision prior to this change.
     * May be null for new page creations.
     */
    private Long old;

    /**
     * The ID of the current revision generated by this change.
     * <p>
     * Mapped from the JSON property "new", which is a reserved keyword in Java.
     * </p>
     */
    @JsonProperty("new")
    private Long newRevision;
}