spring:
  application:
    name: wikimedia-eu-consumer
  kafka:
    bootstrap-servers: # kafka-server
    consumer:
      group-id: wikimedia-eu-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mongodb:
    uri: # mongo uri
  data:
    redis:
      host: #redis server
      port: #redis port
      password: #insert password
wikimedia-eu-consumer:
  topic: wikimedia.recentchange.eu
  group-id: wikimedia-eu-consumer
  excluded-namespaces:
    - "Media"
    - "Berezi"
    - "Eztabaida"
    - "Lankide"
    - "Lankide eztabaida"
    - "Wikipedia"
    - "Wikipedia eztabaida"
    - "Fitxategi"
    - "Fitxategi eztabaida"
    - "MediaWiki"
    - "MediaWiki eztabaida"
    - "Txantiloi"
    - "Txantiloi eztabaida"
    - "Laguntza"
    - "Laguntza eztabaida"
    - "Kategoria"
    - "Kategoria eztabaida"
    - "Atari"
    - "Atari eztabaida"
    - "Wikiproiektu"
    - "Wikiproiektu eztabaida"
    #- "Txikipedia"
    - "Txikipedia eztabaida"
    - "Zerrenda"
    - "Zerrenda eztabaida"
    - "TimedText"
    - "TimedText talk"
    - "Modulu"
    - "Modulu eztabaida"
    - "Event"
    - "Event talk"
    - "Topic"

